"use client";

import { useEffect, useRef, useState, type ReactNode, type TouchEvent } from "react";

const screens = [
  "Home", "Ask Jojo", "Trip Brief", "Flight recommendation", "Flight refinement",
  "Flight selected", "Hotel recommendation", "Hotel selected", "Trip overview",
  "Itinerary", "Collaboration", "Jojo recommendation", "Updated itinerary", "Trip readiness"
] as const;

const photos = {
  ramen: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=900&q=82",
  cafe: "https://images.unsplash.com/photo-1511081692775-05d0f180a065?auto=format&fit=crop&w=900&q=82",
  hotel: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1100&q=84",
  airport: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=82",
  disney: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=900&q=82",
  tokyo: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=82"
};

type Action = () => void;
type Tone = "neutral" | "accent" | "teal" | "blue" | "dark";
type ShellProps = { step: number; children: ReactNode; back?: Action; label?: string; sublabel?: string; jojo?: boolean; bare?: boolean };

function Mark({ small = false }: { small?: boolean }) { return <span className={`jojo-mark ${small ? "small" : ""}`}>j</span>; }
function Status() { return <div className="status"><b>9:41</b><span>●●● &nbsp; Wi-Fi &nbsp; ▰</span></div>; }
function Shell({ step, children, back, label, sublabel, jojo, bare = false }: ShellProps) {
  return <section className="screen" aria-label={screens[step]}><Status />{!bare && <header className="topbar">{back ? <button className="circle" onClick={back}>‹</button> : <span className="circle ghost" />}<div className="topbar-copy">{label && <span className="mono eyebrow">{label}</span>}{sublabel && <span className="subtle">{sublabel}</span>}</div>{jojo ? <Mark /> : <span className="circle ghost" />}</header>}<div className={`content ${bare ? "content-bare" : ""}`}>{children}</div></section>;
}
function Pill({ children, tone = "neutral" }: { children: ReactNode; tone?: Tone }) { return <span className={`pill ${tone}`}>{children}</span>; }
function Button({ children, onClick, primary = false, className = "" }: { children: ReactNode; onClick?: Action; primary?: boolean; className?: string }) { return <button className={`button ${primary ? "primary" : ""} ${className}`} onClick={onClick}>{children}</button>; }
function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`card ${className}`}>{children}</div>; }
function Photo({ src, className = "" }: { src: string; className?: string }) { return <div className={`photo ${className}`} style={{ backgroundImage: `url(${src})` }} />; }
function AvatarStack() { return <div className="avatars"><i>N</i><i>M</i><i>A</i><i>+1</i></div>; }
function JojoNote({ children, title = "JOJO" }: { children: ReactNode; title?: string }) { return <div className="jojo-note"><Mark small /><div><span className="mono eyebrow accent-text">{title}</span>{children}</div></div>; }

function FlightCard({ refined = false }: { refined?: boolean }) {
  return <Card className="flight-card"><div className="row between"><Pill tone={refined ? "teal" : "accent"}>{refined ? "UPDATED" : "BEST FIT"}</Pill>{refined && <Pill>SAVE RP 6.6M</Pill>}</div><h3>Garuda Indonesia</h3><span className="mono meta">NONSTOP · CGK → HND</span><div className="route"><div><strong>{refined ? "08:10" : "07:05"}</strong><span className="mono meta">JAKARTA</span></div><div className="route-line"><span>{refined ? "7H 10M" : "7H 05M"}</span></div><div className="end"><strong>{refined ? "17:20" : "16:10"}</strong><span className="mono meta">TOKYO</span></div></div><hr /><p className="subtle">2 checked bags · Meals · Daytime arrival</p><strong className="price">{refined ? "Rp 42.0m total" : "Rp 48.6m total"}</strong><span className="mono meta">4 TRAVELERS · ROUND TRIP</span></Card>;
}
function HotelCard({ selected = false }: { selected?: boolean }) {
  return <Card className="hotel-card"><div className="hotel-photo"><Photo src={photos.hotel} />{!selected && <Pill tone="accent">BEST FIT</Pill>}</div><div className="hotel-copy"><h3>Hotel Metropolitan Tokyo Marunouchi</h3><span className="mono meta">TOKYO STATION · 4 MIN WALK</span><p className="subtle">Family room · 2 beds + sofa</p><strong className="price">Rp 18.4m · 6 nights</strong>{!selected && <div className="why">Why it fits: easy Disney access, luggage-friendly transfer, late food nearby.</div>}</div></Card>;
}
function BottomNav() { return <nav className="bottom-nav"><button className="active">⌂ <span>Home</span></button><button>◇</button><button>♡</button><button>◎</button></nav>; }

function Home({ next }: { next: Action }) { return <Shell step={0} bare><div className="home-head"><div><span className="mono eyebrow">WELCOME</span><h2>Nadya Angkasa</h2></div><span className="avatar-one">NA</span></div><Card className="ask-card"><JojoNote><h3>Where are you thinking of going?</h3></JojoNote><p className="subtle">Tell me what you know. I’ll help figure out the rest.</p><button className="ask-input" onClick={next}><span>Ask Jojo about a trip...</span><b>↑</b></button></Card><div className="section-title"><span className="mono eyebrow">YOUR TRIPS</span><h2>Jump back in</h2></div><Card className="trip-card"><div><Pill tone="teal">Upcoming</Pill><h3>Lisbon long weekend</h3><span className="mono meta">JUN 21–25 · PORTUGAL</span></div><AvatarStack /></Card><Button onClick={next}>Plan a new trip</Button><div className="section-title"><span className="mono eyebrow">RECENTLY SAVED</span><h2>Spots you’ve caught</h2></div><div className="saved-grid"><Card><Photo src={photos.ramen} /><strong>Ramen for lunch</strong><span className="mono meta">TOKYO</span></Card><Card><Photo src={photos.cafe} /><strong>Café Kitsuné</strong><span className="mono meta">OMOTESANDO</span></Card></div><BottomNav /></Shell>; }
function Ask({ next, back }: { next: Action; back: Action }) { return <Shell step={1} back={back} jojo label="ASK JOJO"><h1>Start with the trip, not the filters.</h1><p className="lead">Tell Jojo the messy version. Dates, people, priorities, and worries can all live in one place.</p><Card className="prompt-card"><span className="mono eyebrow">YOUR TRIP</span><p>Tokyo with the kids, around Feb 14–20. Four of us from Jakarta. DisneySea is a must. I’d rather pay a little more for a direct flight and a hotel that makes the week easy.</p></Card><div className="chips"><Pill>4 travelers</Pill><Pill>Jakarta</Pill><Pill>Tokyo</Pill><Pill tone="accent">DisneySea</Pill><Pill>Direct flight preferred</Pill></div><JojoNote><p>I can work with that. I’ll turn it into a brief before I search anything.</p></JojoNote><Button primary className="full" onClick={next}>Build the trip brief</Button></Shell>; }
function Brief({ next, back }: { next: Action; back: Action }) { const rows: Array<[string,string]> = [["DATES","Feb 14–20 · flexible by 1 day"],["TRAVELERS","2 adults · 2 kids"],["NON-NEGOTIABLE","DisneySea · family-friendly pace"],["PREFERENCE","Nonstop flight · useful hotel location"],["TRADE-OFF","Spend more when it buys an easier day"]]; return <Shell step={2} back={back} jojo label="TRIP BRIEF" sublabel="Tokyo · 4 travelers"><h1>Here’s what I’m optimizing for.</h1><p className="lead">Nothing is booked yet. You can still change the brief before Jojo recommends anything.</p><div className="brief-list">{rows.map(([a,b]) => <Card key={a}><span className="mono eyebrow">{a}</span><strong>{b}</strong></Card>)}</div><Card className="quiet-card"><span className="mono eyebrow accent-text">JOJO’S READ</span><p>This sounds like an ease-first family trip, not a lowest-price trip.</p></Card><Button primary className="full" onClick={next}>Find the best flight</Button></Shell>; }
function FlightRecommendation({ refine, back, choose }: { refine: Action; back: Action; choose: Action }) { return <Shell step={3} back={back} jojo label="TOKYO FAMILY TRIP" sublabel="Feb 14–21 · 4 travelers"><span className="mono eyebrow accent-text">JOJO RECOMMENDS</span><h1>I’d take this one.</h1><p className="lead">It costs more than the cheapest option, but it avoids the exact trade-offs you said you don’t want.</p><FlightCard /><Card className="why-card"><span className="mono eyebrow teal-text">WHY THIS ONE</span><strong>Nonstop · lands before dinner · luggage included</strong><p className="subtle">The cheapest saves Rp 2.8m, but lands after 23:00 and checked bags cost extra.</p></Card><div className="button-row"><Button primary onClick={choose}>Choose this</Button><Button>Show another</Button><Button onClick={refine}>Too expensive</Button></div></Shell>; }
function FlightRefinement({ next, back }: { next: Action; back: Action }) { return <Shell step={4} back={back} jojo label="REFINING FLIGHTS"><h1>We can lower the price without making the trip harder.</h1><p className="lead">Leaving one day earlier keeps the nonstop flight and a daytime arrival.</p><FlightCard refined /><Card className="quiet-card"><span className="mono eyebrow">WHAT CHANGED</span><p>Depart Friday instead of Saturday. Same luggage, same nonstop preference, better total price.</p></Card><div className="button-row"><Button primary onClick={next}>Take this flight</Button><Button onClick={back}>Keep Saturday</Button></div></Shell>; }
function FlightSelected({ next, back }: { next: Action; back: Action }) { return <Shell step={5} back={back} jojo label="TOKYO FAMILY TRIP"><Pill tone="teal">FLIGHT SELECTED</Pill><h1>Great. Now the rest of the trip has context.</h1><p className="lead">Jojo can use the actual arrival time and airport when choosing where you stay and how the first day should work.</p><FlightCard refined /><div className="context-list"><Card><span className="mono eyebrow">ARRIVAL</span><strong>Fri · 17:20 at Haneda</strong></Card><Card><span className="mono eyebrow">FIRST-NIGHT NEED</span><strong>Easy luggage transfer + late dinner nearby</strong></Card></div><Button primary className="full" onClick={next}>Recommend a hotel</Button></Shell>; }
function HotelRecommendation({ next, back }: { next: Action; back: Action }) { return <Shell step={6} back={back} jojo label="TOKYO FAMILY TRIP"><span className="mono eyebrow accent-text">JOJO RECOMMENDS</span><h1>I’d stay near Tokyo Station.</h1><p className="lead">It keeps airport transfer simple, works better for Disney, and gives you direct trains without making every day about Shinjuku.</p><HotelCard /><span className="mono eyebrow block">TWO ALTERNATIVES</span><div className="alt-grid"><Card><strong>Mitsui Garden</strong><span className="mono meta">CHEAPER · +8 MIN</span><b>Rp 15.9m</b></Card><Card><strong>HOSHINOYA</strong><span className="mono meta">MORE SPECIAL</span><b>Rp 31.5m</b></Card></div><Button primary className="full" onClick={next}>Choose this hotel</Button></Shell>; }
function HotelSelected({ next, back }: { next: Action; back: Action }) { return <Shell step={7} back={back} jojo label="STAY ADDED"><Pill tone="teal">HOTEL SELECTED</Pill><h1>Your hotel now shapes the itinerary.</h1><HotelCard selected /><div className="context-list"><Card><span className="mono eyebrow">CHECK-IN</span><strong>Added after arrival</strong></Card><Card><span className="mono eyebrow">HOME BASE</span><strong>Tokyo Station</strong></Card><Card><span className="mono eyebrow">NEARBY IDEAS</span><strong>Ginza + Toyosu fit naturally</strong></Card></div><Button primary className="full" onClick={next}>View my trip</Button></Shell>; }
function TripOverview({ next, back }: { next: Action; back: Action }) { return <Shell step={8} back={back}><div className="overview-head"><AvatarStack /><Pill>Planning</Pill><h1>Tokyo with the kids</h1><span className="mono meta">FEB 13–20 · JAPAN · 4 TRAVELERS</span></div><Card className="native-item"><div><span className="mono eyebrow accent-text">FLIGHT</span><strong>Garuda · CGK → HND</strong><p>Fri 08:10 → 17:20</p></div><Pill tone="teal">Selected</Pill></Card><Card className="native-item"><div><span className="mono eyebrow teal-text">STAY</span><strong>Hotel Metropolitan Marunouchi</strong><p>Tokyo Station · 6 nights</p></div><Pill>Added</Pill></Card><Card className="quiet-card"><JojoNote><p>The big decisions are anchored. Now we can shape the week around Disney, food, and what everyone saves.</p></JojoNote></Card><div className="alt-grid"><Card><strong>Itinerary</strong><span className="mono meta">7 DAYS · 3 ITEMS</span></Card><Card><strong>Shortlist</strong><span className="mono meta">6 SAVED IDEAS</span></Card></div><Button primary className="full" onClick={next}>View itinerary</Button></Shell>; }

function DayChips({ updated = false }: { updated?: boolean }) { return <div className="day-chips"><div>▱<small className="mono">9 ITEMS</small></div><div><small className="mono">FRI</small><b>13</b><small className="mono">3 ITEMS</small></div><div className="selected"><small className="mono">SAT</small><b>14</b><small className="mono">{updated ? "4 ITEMS" : "5 ITEMS"}</small></div><div><small className="mono">SUN</small><b>15</b><small className="mono">2 ITEMS</small></div></div>; }
function Event({ time, end, type, title, sub, image, tone = "neutral" }: { time: string; end: string; type: string; title: string; sub: string; image: string; tone?: Tone }) { return <div className="event"><div className="time mono"><span>{time}</span><span>{end}</span></div><Card className="event-card"><div><Pill tone={tone}>{type}</Pill><h4>{title}</h4><p>{sub}</p></div><Photo src={image} /></Card></div>; }
function ItineraryBase({ updated = false }: { updated?: boolean }) { return <><div className="itinerary-title"><Pill>Planning</Pill><h2>Tokyo with the kids</h2><span className="mono meta">FEB 13 – FEB 20 | JAPAN</span></div><DayChips updated={updated} /><div className="unscheduled"><span>◷</span><span className="mono">UNSCHEDULED (3)</span><span>⌃</span></div><div className="unscheduled-cards"><Card><strong>Ramen for lunch</strong><span>Afuri Harajuku</span></Card><Card><strong>Coffee and chill</strong><span>Kurasu</span></Card></div><div className="events"><Event time="08:10" end="17:20" type="FLIGHT" title="Arrive in Tokyo" sub="Haneda Airport, Tokyo" image={photos.airport} tone="accent" /><Event time="18:30" end="19:00" type="STAY" title="Check-in to hotel" sub="Hotel Metropolitan Tokyo Marunouchi" image={photos.hotel} /><div className="free"><span className="mono">1H 45M FREE</span><Pill tone="blue">TAP TO FILL</Pill></div><Event time="10:00" end="20:00" type="ACTIVITY" title="Tokyo DisneySea" sub="Maihama, Urayasu" image={photos.disney} tone="teal" />{updated && <Event time="17:30" end="19:30" type="ACTIVITY" title="TeamLab Planets" sub="Moved to Thursday · Toyosu" image={photos.tokyo} tone="teal" />}</div></>; }
function Itinerary({ next, back }: { next: Action; back: Action }) { return <Shell step={9} bare><div className="native-top"><button className="circle" onClick={back}>‹</button><AvatarStack /><button className="circle">•••</button></div><ItineraryBase /><button className="floating-next" onClick={next}>Continue</button></Shell>; }
function Collaboration({ next, back }: { next: Action; back: Action }) { return <Shell step={10} bare><div className="native-top"><button className="circle" onClick={back}>‹</button><AvatarStack /><button className="circle">•••</button></div><ItineraryBase /><div className="sheet"><i className="grabber" /><div className="collab-head"><span className="avatar-green">M</span><div><span className="mono eyebrow">MATT · JUST NOW</span><strong>saved Sushi Dai</strong></div></div><Card className="saved-event"><span className="mono eyebrow">FOOD & DRINK</span><strong>Sushi Dai · Toyosu</strong><small>Saved to Tokyo shortlist</small></Card><JojoNote title="JOJO NOTICED"><p>This fits neatly after your Ginza afternoon on Thursday — about 18 minutes away.</p></JojoNote><Button primary className="full" onClick={next}>Add after Ginza</Button></div></Shell>; }
function Proactive({ next, back }: { next: Action; back: Action }) { return <Shell step={11} bare><div className="native-top"><button className="circle" onClick={back}>‹</button><AvatarStack /><button className="circle">•••</button></div><ItineraryBase /><div className="sheet proactive"><i className="grabber" /><JojoNote title="JOJO · ITINERARY CHECK"><span /></JojoNote><h2>Tuesday is looking crowded.</h2><p className="lead">DisneySea plus TeamLab will probably be too much with the kids. I’d move TeamLab to Thursday and keep Tuesday focused on Disney.</p><span className="mono eyebrow block">PROPOSED CHANGE</span><div className="proposal"><Pill tone="accent">TUE</Pill><strong>TeamLab · 17:30</strong></div><div className="proposal to"><Pill tone="teal">THU</Pill><strong>TeamLab · 17:30</strong></div><Button primary className="full" onClick={next}>Fix the day</Button></div></Shell>; }
function Updated({ next, back }: { next: Action; back: Action }) { return <Shell step={12} bare><div className="native-top"><button className="circle" onClick={back}>‹</button><AvatarStack /><button className="circle">•••</button></div><ItineraryBase updated /><div className="update-banner"><Mark small /><div><span className="mono eyebrow teal-text">UPDATED</span><strong>Tuesday feels better now.</strong><small>TeamLab is on Thursday at 17:30.</small></div></div><button className="floating-next wide" onClick={next}>Before you go</button></Shell>; }
function Readiness({ back }: { back: Action }) { const items: ReadonlyArray<readonly [string,string,string,string,Tone]> = [["Passport & entry","3 ready · 1 needs a check","One child passport expires within 8 months. Check entry guidance.","CHECK","accent"],["Travel insurance","Not added yet","Your hotel and flight are selected, so coverage can now be compared accurately.","VIEW","neutral"],["Connectivity","4 devices","You’ll need data for four devices. View eSIM options for Japan.","VIEW","teal"],["Airport transfer","Haneda → Tokyo Station","Best fit: airport limousine bus with luggage, ~40 min.","READY","blue"]]; return <Shell step={13} back={back} jojo label="TOKYO WITH THE KIDS"><h1>Before you go</h1><p className="lead">Only surface what matters for this trip, when it matters.</p><Card className="progress-card"><div><span className="mono eyebrow">TRIP READINESS</span><strong>3 of 4 areas look good</strong></div><Pill tone="teal">ON TRACK</Pill></Card><div className="readiness-list">{items.map(([title,meta,copy,tag,tone]) => <Card key={title} className="readiness"><div className="row between"><div><strong>{title}</strong><span className="mono meta">{meta}</span></div><Pill tone={tone}>{tag}</Pill></div><p className="subtle">{copy}</p></Card>)}</div><div className="jojo-end"><Mark small /><div><strong>Nothing urgent today.</strong><p>I’ll keep watching the trip context.</p><span className="mono eyebrow accent-text">JOJO</span></div></div></Shell>; }

export function OtterWayPrototype() {
  const [step, setStep] = useState(0);
  const touch = useRef<number | null>(null);
  const go = (n: number) => setStep(Math.max(0, Math.min(screens.length - 1, n)));
  const next = () => go(step + 1);
  const back = () => go(step - 1);
  useEffect(() => { window.scrollTo({ top: 0, behavior: "smooth" }); }, [step]);

  let view: ReactNode;
  switch (step) {
    case 0: view = <Home next={next} />; break;
    case 1: view = <Ask next={next} back={back} />; break;
    case 2: view = <Brief next={next} back={back} />; break;
    case 3: view = <FlightRecommendation refine={() => go(4)} choose={() => go(5)} back={back} />; break;
    case 4: view = <FlightRefinement next={() => go(5)} back={back} />; break;
    case 5: view = <FlightSelected next={next} back={back} />; break;
    case 6: view = <HotelRecommendation next={next} back={back} />; break;
    case 7: view = <HotelSelected next={next} back={back} />; break;
    case 8: view = <TripOverview next={next} back={back} />; break;
    case 9: view = <Itinerary next={next} back={back} />; break;
    case 10: view = <Collaboration next={next} back={back} />; break;
    case 11: view = <Proactive next={next} back={back} />; break;
    case 12: view = <Updated next={next} back={back} />; break;
    default: view = <Readiness back={back} />;
  }

  const onTouchStart = (event: TouchEvent<HTMLDivElement>) => { touch.current = event.touches[0]?.clientX ?? null; };
  const onTouchEnd = (event: TouchEvent<HTMLDivElement>) => {
    if (touch.current === null) return;
    const delta = (event.changedTouches[0]?.clientX ?? touch.current) - touch.current;
    if (delta < -80) next();
    if (delta > 80) back();
    touch.current = null;
  };

  return <main className="stage"><aside className="desktop-copy"><span className="mono eyebrow">OTTERWAY</span><h1>Intelligent travel prototype</h1><p>Mobile-first stakeholder demo. Use in-app CTAs, swipe, or arrow controls.</p><div className="desktop-progress"><b>{String(step + 1).padStart(2, "0")}</b><div><strong>{screens[step]}</strong><small>{step + 1} / {screens.length}</small></div></div></aside><div className="phone" key={step} onTouchStart={onTouchStart} onTouchEnd={onTouchEnd}>{view}</div><div className="desktop-controls"><button onClick={back} disabled={step === 0}>←</button><div>{screens.map((_, i) => <i key={i} className={i === step ? "now" : i < step ? "done" : ""} />)}</div><button onClick={next} disabled={step === screens.length - 1}>→</button></div></main>;
}
